[module]
name = "Simple Editor"
url = "https://github.com/rescile/module-simple-editor"
version = "0.0.1"
description = "Simple CSV Editor to edit asset files directly in the browser."
rescile_version = ">=0.1.114"
